name: Deploy S3 static - default
on:
  workflow_call:
    inputs:
      env_file:
        default: ".env.development"
        required: false
        type: string
      source_dir:
        default: "dist"
        required: false
        type: string
      destination_bucket:
        required: true
        type: string
      destination_dir:
        default: "" # upload to bucket root
        required: false
        type: string
      endpoint:
        default: "https://s3.eu-central-1.amazonaws.com"
        required: false
        type: string
      timeout:
        default: "5m0s"
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        if: ${{ hashFiles('yarn.lock') != '' }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      - name: Install dependencies from lock
        if: ${{ hashFiles('yarn.lock') != '' }}
        run: yarn install --immutable
      - name: Copy env file to .env if provided
        if: ${{ hashFiles('package.json') != '' }}
        run: touch ${{ inputs.env_file }} && cp ${{ inputs.env_file }} .env && cat .env
      - name: Build production bundle
        if: ${{ hashFiles('package.json') != '' }}
        run: yarn run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.ref_name }}-${{ github.sha }}"
          path: ${{ inputs.source_dir }}

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "${{ github.ref_name }}-${{ github.sha }}"
          path: ${{ inputs.source_dir }}

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key}}
          aws_bucket: ${{ inputs.destination_bucket }}
          source_dir: ${{ inputs.source_dir }}
          destination_dir: ${{ inputs.destination_dir }}
          endpoint: ${{ inputs.endpoint }}
